apiVersion: batch/v1
kind: Job
metadata:
  name: akeyless-retrieval-job
  namespace: akeyless-k8s-python-demo
spec:
  template:
    spec:
      serviceAccountName: akeyless-python-sa
      containers:
      - name: python-app
        image: leonmaister/akeyless-k8s-python-demo:2.0-sdk
        imagePullPolicy: Always
      restartPolicy: Never 
  backoffLimit: 2 